services:

  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    restart: always
    hostname: "gitlab.ajwrap.com"

    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://gitlab.ajwrap.com"
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp"
        gitlab_rails['smtp_port'] = 1025
        gitlab_rails['smtp_domain'] = "ajwrap.com"
        gitlab_rails['gitlab_email_from'] = "noreply@ajwrap.com"

    ports:
      - "80:80"
      - "443:443"
      - "22:22"

    volumes:
      - "${GITLAB_HOME}/config:/etc/gitlab"
      - "${GITLAB_HOME}/logs:/var/log/gitlab"
      - "${GITLAB_HOME}/data:/var/opt/gitlab"

    shm_size: "256m"

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    depends_on:
      - gitlab
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./gitlab-runner-config:/etc/gitlab-runner"

  smtp:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"

